objects/Lead_Assessment_Condition__c.object
<CustomObject>
    <fields>
        <fullName>Condition_Filter__c</fullName>
        <label>Condition Filter</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>!=</fullName>
                </value>
                <value>
                    <fullName>&lt;</fullName>
                </value>
                <value>
                    <fullName>&lt;=</fullName>
                </value>
                <value>
                    <fullName>=</fullName>
                </value>
                <value>
                    <fullName>&gt;</fullName>
                </value>
                <value>
                    <fullName>&gt;=</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>LIKE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Condition_Name__c</fullName>
        <formula>Lead_Assessment_Query__r.Condition_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Condition Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Condition_Value__c</fullName>
        <label>Condition Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Assessment_Query__c</fullName>
        <label>Lead Assessment Query</label>
        <referenceTo>Lead_Assessment_Query__c</referenceTo>
        <relationshipLabel>Lead Assessment Conditions</relationshipLabel>
        <relationshipName>Lead_Assessment_Conditions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Lead_Assessment_Rule__c</fullName>
        <label>Lead Assessment Rule</label>
        <referenceTo>Lead_Assessment_Rule__c</referenceTo>
        <relationshipLabel>Lead Assessment Conditions</relationshipLabel>
        <relationshipName>Lead_Assessment_Conditions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Lead Assessment Condition</label>
    <nameField>
        <displayFormat>CONDITION-{00000}</displayFormat>
        <label>Lead Assesment Condition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Assessment Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Lead_Assessment_Query__c.object
<CustomObject>
    <fields>
        <fullName>Condition_Name__c</fullName>
        <externalId>true</externalId>
        <label>Condition Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Query_Piece__c</fullName>
        <description>For matching lead field key in complex queries, please use [key] syntax.</description>
        <inlineHelpText>For matching lead field key in complex queries, please use [key] syntax.</inlineHelpText>
        <label>Query Piece</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Lead Assessment Query</label>
    <nameField>
        <displayFormat>QUERY-{000}</displayFormat>
        <label>Lead Assesment Query Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Assessment Queries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead_Assessment_Rule__c.object
<CustomObject>
    <fields>
        <fullName>Lead_Assessment_Type__c</fullName>
        <label>Lead Assessment Type</label>
        <referenceTo>Lead_Assessment_Type__c</referenceTo>
        <relationshipLabel>Lead Assessment Rules</relationshipLabel>
        <relationshipName>Lead_Assesment_Rules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Lead Assessment Rule</label>
    <nameField>
        <label>Lead Assessment Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Assessment Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Lead_Assessment_Type__c.object
<CustomObject>
    <fields>
        <fullName>Record_Type__c</fullName>
        <label>Record Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>B2C Housing Sales</fullName>
                </value>
                <value>
                    <fullName>Tenant Candidate</fullName>
                </value>
                <value>
                    <fullName>Workery+</fullName>
                </value>
                <value>
                    <fullName>1. YIT Lead</fullName>
                </value>
                <value>
                    <fullName>2. Business Premises - RED</fullName>
                </value>
                <value>
                    <fullName>3. Infra Services</fullName>
                </value>
                <value>
                    <fullName>4. Municipality Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Lead Assessment Type</label>
    <nameField>
        <displayFormat>TYPE-{00}</displayFormat>
        <label>Lead Assesment Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Assessment Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LeadAssessmentServiceTest.cls
@IsTest
public with sharing class LeadAssessmentServiceTest {
    @TestSetup
    public static void setup(){
        Lead_Assessment_Type__c type = new Lead_Assessment_Type__c();
        type.Record_Type__c = 'B2C Housing Sales';
        insert type;

        Lead_Assessment_Rule__c rule = new Lead_Assessment_Rule__c();
        rule.Lead_Assessment_Type__c = type.Id;

        insert rule;

        Lead_Assessment_Query__c query = new Lead_Assessment_Query__c();
        query.Query_Piece__c = 'Name';
        query.Condition_Name__c = 'test condition';
        insert query;

        Lead_Assessment_Condition__c condition = new Lead_Assessment_Condition__c();
        condition.Lead_Assessment_Rule__c = rule.Id;
        condition.Lead_Assessment_Query__c = query.Id;
        condition.Condition_Filter__c = '=';
        condition.Condition_Value__c = 'Ryszard';
        insert condition;

    }
    @IsTest
    public static void verifyQueriesTest(){
        Lead_Assessment_Rule__c rule = [SELECT Id FROM Lead_Assessment_Rule__c];
        System.assert(LeadAssessmentService.verifyQueriesAndActions(rule.Id) != null);
    }
}